fasterrcnn_resnet50_fpn:
      model_path: torchvision.models.detection.fasterrcnn_resnet50_fpn
      num_classes: 91

fasterrcnn_mobilenet_v3_large_fpn:
     model_path: torchvision.models.detection.fasterrcnn_mobilenet_v3_large_fpn
     num_classes: 91

fasterrcnn_mobilenet_v3_large_320_fpn:
      model_path: torchvision.models.detection.fasterrcnn_mobilenet_v3_large_320_fpn
      num_classes: 91

fcos_resnet50_fpn:
      model_path: torchvision.models.detection.fcos_resnet50_fpn
      num_classes: 91

retinanet_resnet50_fpn:
    - model_path: torchvision.models.detection.retinanet_resnet50_fpn
    - num_classes: 91

ssd300_vgg16:
    - model_path: torchvision.models.detection.ssd300_vgg16
    - num_classes: 91


ssdlite320_mobilenet_v3_large:
    - model_path: torchvision.models.detection.ssdlite_mobilenet_v3_large
    - num_classes: 91


maskrcnn_resnet50_fpn:
    - model_path: torchvision.models.detection.maskrcnn_resnet50_fpn
    - num_classes: 91
    